### ISSUE TITLE
Syllable stress not parsing correctly

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#21]
It seems that the output of syllable enrichment results in some funky-looking stress patterns. For example, 'the' seems to have `1-0` stress pattern (extracted from SOTC):
```
speaker,syllable_label,syllable_duration,word,stress_pattern,num_syllables,style,agegroup,gender,recording_decade
00-O-m05-dock,D.i,0.14999999999997726,the,1-0,1,,,,
00-O-m05-dock,D.i,0.08000000000004093,the,1-0,1,,,,
00-O-m05-dock,D.i,0.11000000000012733,"the,",,1,,,,
00-O-m05-dock,D.i,0.12000000000000455,the,1-0,1,,,,
00-O-m05-dock,D.i,0.13999999999998636,the,1-0,1,,,,
00-O-m05-dock,D.i,0.21000000000003638,the,1-0,1,,,,
00-O-m05-dock,D.i,0.14959999999996398,the,1-0,1,,,,
00-O-m05-dock,D.i,0.18000000000006366,the,1-0,1,,,,
00-O-m05-dock,D.i,0.06999999999993634,the,1-0,1,,,,
```
Whilst 'for' gets `0-0-1-0`:
```
80-Y-f01,Q.v,0.06999999999993634,of,0-0-1-0,1,Vernacular,Young,F,1980s
80-Y-f01,Q.v,0.12000000000034561,of,0-0-1-0,1,Vernacular,Young,F,1980s
80-Y-f01,Q.v,0.07999999999992724,of,0-0-1-0,1,Vernacular,Young,F,1980s
80-Y-f01,Q.v,0.05999999999994543,of,0-0-1-0,1,Vernacular,Young,F,1980s
```

These were made with my `unisyn_spade` repo up to date - does it need any further steps (e.g., rebuilidng etc)?

**Comment by james-tanner** [comment]
So I just retried this after rebuilding the dictionaries following MG's updates, but the stress-patterns are still really weird (from Hastings):
```
phone_label,word_unisyn,word_label,word_stresspattern,syllable_stress
AA1,o,DROP,D.R.AA1.P,1-0,,
OW1,ou,MOST,M.OW1.S,,,
UW1,uu,PUKE,P.Y.UW1.K,1-0,,
````
It's clearly not an actual problem with the pronunciation dictionaries though, since the rebuilt one looks correct:
```
drop,o,o,Q,1,False,False,False,False,False,False,False,0
most,ou,ou,@U,1,False,False,False,False,False,False,False,0
puke,uu,uu,u:,1,False,False,False,False,False,False,False,0
```
I reset and reimported everything prior to exporting again, so perhaps this has something to do with how polyglot is extracting stress patterns from the lexicon?

**Comment by james-tanner** [comment]
I think I got it working! I just needed to update the dictionaries inside my `unisyn_spade` repo. Will check with other datasets and then close if confirmed.

**Comment by james-tanner** [comment]
Updating dictionaries for other dialects also fixed it, so will close this and make a PR of updated dictionaries to `unisyn_spade`.

**Comment by msonderegger** [comment]
Hooray!  Nice work.

On Sun, Jun 16, 2019 at 2:18 AM James Tanner <notifications@github.com<mailto:notifications@github.com>> wrote:

Updating dictionaries for other dialects also fixed it, so will close this and make a PR of updated dictionaries to unisyn_spade.
