### ISSUE TITLE
Punctuation in words

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#22]
The word output from corpora like SOTC have punctuation in them, which results in them being treated as separate words from their clean counterparts. For example, `the` extracted here has different information from `"the,"`, where it is missing (incorrect) syllable information:

```
00-O-m05-dock,D.i,0.14999999999997726,the,1-0,1,,,,
00-O-m05-dock,D.i,0.08000000000004093,the,1-0,1,,,,
00-O-m05-dock,D.i,0.11000000000012733,"the,",,1,,,,
```
Perhaps this could be fixed with stripping the tokens inside the word tiers in the TextGrids?

**Comment by james-tanner** [comment]
This has now been fixed in the SOTC repository.

**Comment by msonderegger** [comment]
great!
