### ISSUE TITLE
Vowel prototype files -> dataset repositories

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/SPADE#3]
Each dataset repository (hosted at CS) should have a vowel prototype CSV among the files in the "enrichment" subdirectory. These are the files like
`ICECAN_prototypes.csv`
that's currently in 
`SPADE/ICECAN/` dir of this (Github) repository. Etc.

so these need to be checked in to CS repos, and a note for yourself added that this file is needed for any new corpus.

**Comment by vannawillerton** [comment]
This is done, but apparently you need to be a collaborator on a repo to close an issue through the web interface without a commit. Could you close it or make me a collaborator, please?
