### ISSUE TITLE
Edinburgh parses pauses as phones

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#35]
Running `duration.py` on the Edinburgh corpus outputs an empty CSV, whilst running `polysyllabic.py` indicates that pauses are being parsed as phones:

```
speakers,syllable_label,syllable_duration,word_label,syllable_stress,word_num_segments
R0368,<p:>,0.21567000000000291,<SIL>,,1
R0427,<p:>,1.9041899999999998,<SIL>,,1
R0498,<p:>,0.3558500000000038,<SIL>,,1
R0070,<p:>,0.4505800000000022,<SIL>,,1
R0287,<p:>,0.195769999999996,<SIL>,,1
R0072,<p:>,0.3589600000000104,<SIL>,,1
R0557,<p:>,0.36659999999999116,<SIL>,,1
R0443,<p:>,0.49044000000000665,<SIL>,,1
R0127,<p:>,0.8302100000000223,<SIL>,,1
```

**Comment by mmcauliffe** [comment]
The yaml file has `'^<p:>$'` as the pause, but that looks to be the pause phone, so `^<SIL>$` or `['<SIL>']` (and any other pause words) would be the way to specify it.

**Comment by james-tanner** [comment]
That worked! Silly error on my part. Closing.
