### ISSUE TITLE
NAs in formant points

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#45]
Having extracted formant tracks for ICE-Canada, I've noticed that about 12% vowels contain at least some of points that have NA values for all F{1,2,3}. First I thought this might be due to the effects of consonants on either edge, but there are NAs for samples taken within the middle of the vowel, e.g.,:
```
> filter(icecan, is.na(F1)) %>% select(phone_id, time, F1, F2, F3) %>% head
                              phone_id time F1 F2 F3
1 57fb4cf0-a353-11e9-a342-989096dd3426 0.20 NA NA NA
2 57fb4cf0-a353-11e9-a342-989096dd3426 0.25 NA NA NA
3 57fb4cf0-a353-11e9-a342-989096dd3426 0.30 NA NA NA
4 57fb4cf0-a353-11e9-a342-989096dd3426 0.35 NA NA NA
5 57fb4cf0-a353-11e9-a342-989096dd3426 0.40 NA NA NA
6 57fb4cf0-a353-11e9-a342-989096dd3426 0.45 NA NA NA
```
Any idea why this might be?

**Comment by mmcauliffe** [comment]
This is probably working as intended, since there's probably quite a few tokens of the vowel type per speaker that fall below the 6 tokens necessary for refined formants.  You can double check that.  ICE-Canada by its nature as a radio corpus with call in speakers probably has more of this than other corpora.  If there's NA tracks that don't fall into that category, then double check the waveform either in ISCAN or Praat.  @msonderegger this is within your expectations too, right?

**Comment by james-tanner** [comment]
If there are insufficient tokens, would that vowel still be included in the CSV? I suppose that the query is just being done on all vowels in the unisyn subset regardless of their formant values.

Also I've seen that:
1. this is not exclusive to ICE-Can
2. for some tokens only a subset of tokens have NAs whilst the rest have values
For example, this is a token from Modern RP:
```
> rp %>% filter(phone_id == "f8697b28-8fa1-11e9-a342-989096dd3426") %>%
group_by(time) %>% select(phone_id, time, F1, F2, F3) %>% print.data.frame
                               phone_id time      F1       F2       F3
1  f8697b28-8fa1-11e9-a342-989096dd3426 0.00      NA       NA       NA
2  f8697b28-8fa1-11e9-a342-989096dd3426 0.05      NA       NA       NA
3  f8697b28-8fa1-11e9-a342-989096dd3426 0.10      NA       NA       NA
4  f8697b28-8fa1-11e9-a342-989096dd3426 0.15 620.436 2025.700 2782.934
5  f8697b28-8fa1-11e9-a342-989096dd3426 0.20 621.508 2059.620 2815.382
6  f8697b28-8fa1-11e9-a342-989096dd3426 0.25 622.580 2093.540 2847.830
7  f8697b28-8fa1-11e9-a342-989096dd3426 0.30 617.912 2085.724 2816.278
8  f8697b28-8fa1-11e9-a342-989096dd3426 0.35 613.244 2077.908 2784.726
9  f8697b28-8fa1-11e9-a342-989096dd3426 0.40 609.214 2099.112 2778.246
10 f8697b28-8fa1-11e9-a342-989096dd3426 0.45 605.822 2149.336 2796.838
11 f8697b28-8fa1-11e9-a342-989096dd3426 0.50 602.430 2199.560 2815.430
12 f8697b28-8fa1-11e9-a342-989096dd3426 0.55 594.294 2215.784 2795.934
13 f8697b28-8fa1-11e9-a342-989096dd3426 0.60 586.158 2232.008 2776.438
14 f8697b28-8fa1-11e9-a342-989096dd3426 0.65 581.424 2270.026 2804.966
15 f8697b28-8fa1-11e9-a342-989096dd3426 0.70 580.092 2329.838 2881.518
16 f8697b28-8fa1-11e9-a342-989096dd3426 0.75 578.760 2389.650 2958.070
17 f8697b28-8fa1-11e9-a342-989096dd3426 0.80 575.956 2425.506 2936.286
18 f8697b28-8fa1-11e9-a342-989096dd3426 0.85 573.152 2461.362 2914.502
19 f8697b28-8fa1-11e9-a342-989096dd3426 0.90 570.354 2487.364 2915.478
20 f8697b28-8fa1-11e9-a342-989096dd3426 0.95 567.562 2503.512 2939.214
21 f8697b28-8fa1-11e9-a342-989096dd3426 1.00 564.770 2519.660 2962.950
```
-----
Looking at bit at Modern RP, the NAs are restricted to being with the first or last 20% of a token (`sample` here is just `time` rounded to 2dp):
```
> rp %>% filter(is.na(F1)) %>% distinct(sample)
  sample
1   0.00
2   0.05
3   0.10
4   0.95
5   1.00
6   0.90
7   0.15
8   0.85
```
This isn't true for ICE-Can though:
```
> icecan %>% filter(is.na(F1)) %>% distinct(sample)
   sample
1    0.00
2    1.00
3    0.05
4    0.10
5    0.15
6    0.20
7    0.25
8    0.30
9    0.35
10   0.40
11   0.45
12   0.50
13   0.55
14   0.60
15   0.65
16   0.70
17   0.75
18   0.80
19   0.85
20   0.90
21   0.95
```

I think it's the case that vowels can either have NAs at the beginning and the end of vowels, or for the whole vowel (i.e., no vowels with NAs at the midpoint with values at the ends). Would this be consistent with the expected behaviour of the refined points algorithm?

**Comment by james-tanner** [comment]
Looking at a specific speaker with a lot of tokens (e.g., Brian Mulroney in ICE-Can), it seems to be the case the same unisyn vowel can have NA-less and NA-full tokens:
```
> icecan %>% filter(speaker == "Brian_Mulroney") %>% select(phone_id, unisyn_vowel, sample, F1)
6910 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.00       NA
6911 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.05       NA
6912 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.10       NA
6913 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.15       NA
6914 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.20       NA
6915 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.25       NA
6916 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.30       NA
6917 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.35       NA
6918 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.40       NA
6919 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.45       NA
6920 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.50       NA
6921 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.55       NA
6922 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.60       NA
6923 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.65       NA
6924 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.70       NA
6925 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.75       NA
6926 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.80       NA
6927 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.85       NA
6928 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.90       NA
6929 d94e2d19-a352-11e9-a342-989096dd3426           ei   0.95       NA
6930 d94e2d19-a352-11e9-a342-989096dd3426           ei   1.00       NA
...
6847 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.00       NA
6848 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.05 478.7220
6849 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.10 484.6886
6850 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.15 477.0056
6851 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.20 469.3967
6852 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.25 463.5296
6853 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.30 461.0466
6854 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.35 462.8120
6855 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.40 462.4962
6856 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.45 453.3052
6857 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.50 444.5842
6858 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.55 439.1128
6859 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.60 447.1988
6860 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.65 451.9878
6861 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.70 455.3927
6862 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.75 462.2892
6863 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.80 473.0152
6864 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.85 486.6748
6865 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.90 501.4558
6866 d94e2eb6-a352-11e9-a342-989096dd3426           ei   0.95 513.9104
6867 d94e2eb6-a352-11e9-a342-989096dd3426           ei   1.00 523.9659

**Comment by mmcauliffe** [comment]
Did you look at the waveforms/spectrograms for these tokens?  It could be that they're too quiet or tracking failed due to noise etc.  ICE-Can also has spectral issues in general, I remember the sibilants all being lower centroid frequency than they should be.  If you can find a token that praat can generate a good track that ISCAN can't, then I'll go from there.

**Comment by james-tanner** [comment]
Yep, fair point.
So checking these so far, it looks like:
- the alignment for `S3A-001_1` (from where the first token in this issue comes) in ICE-Can is completely off (to the point where it needs realigning).
- token `3f685db1-a353-11e9-a342-989096dd3426` from `S2B-050_1` (pictured below) seems to look fairly reasonable (what do you think?)

![Screen Shot 2019-07-13 at 07 09 36](https://user-images.githubusercontent.com/8843358/61170866-576f2280-a53d-11e9-9635-daace6991cf9.png)
looks like this in R:

```
> icecan %>% filter(phone_id == "3f685db1-a353-11e9-a342-989096dd3426") %>% 
select(discourse, phone_begin, phone_end, time, F1, F2, F3)
   discourse phone_begin phone_end time F1 F2 F3
1  S2B-050_1    540.4343  540.4743 0.00 NA NA NA
2  S2B-050_1    540.4343  540.4743 0.05 NA NA NA
3  S2B-050_1    540.4343  540.4743 0.10 NA NA NA
4  S2B-050_1    540.4343  540.4743 0.15 NA NA NA
5  S2B-050_1    540.4343  540.4743 0.20 NA NA NA
6  S2B-050_1    540.4343  540.4743 0.25 NA NA NA
7  S2B-050_1    540.4343  540.4743 0.30 NA NA NA
8  S2B-050_1    540.4343  540.4743 0.35 NA NA NA
9  S2B-050_1    540.4343  540.4743 0.40 NA NA NA
10 S2B-050_1    540.4343  540.4743 0.45 NA NA NA
11 S2B-050_1    540.4343  540.4743 0.50 NA NA NA
12 S2B-050_1    540.4343  540.4743 0.55 NA NA NA
13 S2B-050_1    540.4343  540.4743 0.60 NA NA NA
14 S2B-050_1    540.4343  540.4743 0.65 NA NA NA
15 S2B-050_1    540.4343  540.4743 0.70 NA NA NA
16 S2B-050_1    540.4343  540.4743 0.75 NA NA NA
17 S2B-050_1    540.4343  540.4743 0.80 NA NA NA
18 S2B-050_1    540.4343  540.4743 0.85 NA NA NA
19 S2B-050_1    540.4343  540.4743 0.90 NA NA NA
20 S2B-050_1    540.4343  540.4743 0.95 NA NA NA
21 S2B-050_1    540.4343  540.4743 1.00 NA NA NA
```

For the token from the Modern RP corpus mentioned above (with NAs for first three samples), the spectrogram looks like this:

![Screen Shot 2019-07-13 at 07 19 05](https://user-images.githubusercontent.com/8843358/61170953-86d25f00-a53e-11e9-86df-e22dd3a36b25.png)

I'm much less used to knowing what is likely a good candidate for getting formant measures, so what do you think of these?

@msonderegger As an aside I'm wondering if at least the one file I mentioned above needs re-alignment, since it really doesn't match at all.

**Comment by msonderegger** [comment]
Sorry guys, just getting to this.

On @mmcauliffe 's question, I don't have a sense of whether there will be a _lot_ of speaker/vowel-type pairs with <6 tokens in Ice-Can, but yes it will happen sometimes because there is so little data for some speakers.  So presumably those tokens have NAs, though it would be good for James to verify.

@james : Following Michael's suggestion, I'd suggest posting a number of examples where the waveform + formant tracking looks OK for the whole vowel, but you are getting NAs.  (Like the two above.)  In general if there is modal voicing throughout the whole token and Praat shows continuous formant tracks (like in your examples above), NAs seem odd.

**Comment by james-tanner** [comment]
Thanks @msonderegger. It's a little difficult to check this exactly, but I've tried to find where these cases might be. It looks like there are quite a few cases for speaker-vowel pairs where there are < 6 tokens, but not exclusively so:

```
> icecan %>% filter(is.na(F1) & sample == 0.5) %>% group_by(speaker, phone_label) %>%
summarise(n = n_distinct(phone_id)) %>% filter(n >= 6) %>% print.data.frame
             speaker phone_label   n
1  Audrey_McLaughlin         IY1  12
2     Brian_Mulroney         IY1  17
3          Evan__Bok         AW1   6
4          Evan__Bok         AY1   9
5          Evan__Bok         EY1  27
6          Evan__Bok         IY1  44
7      George_Fraser         IY1  15
8               Gore         IY1  12
9      Greg_Thompson         IY1  12
10     Jack_Babineau         IY1  11
11    Jean__Chretien         IY1  19
12       Jeff_Rankin         AW1   9
13       Jeff_Rankin         AY1  12
14       Jeff_Rankin         EY1  31
15       Jeff_Rankin         IY0   8
16       Jeff_Rankin         IY1  71
17        Mary_Henny         AW1  15
18        Mary_Henny         IY1  10
19    Mike_Carpenter         IY1   7
20    Peter_Milliken         IY0   6
21    Peter_Milliken         IY1   6
22      Roger_Bolton         IY1  28
23   Timmy_Shoemaker         IY1  10
24           unknown         AH0   9
25           unknown         AW1  31
26           unknown         AY1  17
27           unknown         EY1  23
28           unknown         IH0   6
29           unknown         IY0  19
30           unknown         IY1 223
31     W.O._Mitchell         IY1  37
```

It looks as though ~90% of them are where there are less than 6 tokens for a speaker-vowel pair (the above cases are the exceptions). I presume these should be excluded for further analysis, correct?

**Comment by msonderegger** [comment]
The thing to check is whether you have NAs throughout vowels for speaker/word pairs with < 6 tokens.  That will make exclusion necessary/happen automatically.  

 In general I wouldn't exclude data until there's a clear object of analysis (like, if you're analyzing EY and some other vowels, you'll check nTokens per speaker for those and exclude based on some cutoff before analyzing further).  You'll probably want to normalize vowels formants, and assuming you use Lobanov normalization you'll need to calculate F1 and F2 across *all* vowels for a given speaker.

**Comment by james-tanner** [comment]
Some examples for cases with >= 6 speaker-vowel pairs:
Speaker: `Audrey_McLaughlin`; discourse: `S2B-025_1`
![Screen Shot 2019-07-15 at 09 44 33](https://user-images.githubusercontent.com/8843358/61220878-43662500-a6e5-11e9-9ac6-cb9bb9fd170d.png)

![Screen Shot 2019-07-15 at 09 46 03](https://user-images.githubusercontent.com/8843358/61220932-6395e400-a6e5-11e9-86b0-8d3eaff6cbff.png)

Speaker: `Brian_Mulroney`; discourse: `S2B-023_1` (not sure about the recording quality on this one)
![Screen Shot 2019-07-15 at 09 50 57](https://user-images.githubusercontent.com/8843358/61221268-21b96d80-a6e6-11e9-9054-10493af05bfb.png)

I'll try and grab some more later today.

**Comment by msonderegger** [comment]
Seems like enough for MM to look into and can let you know if more needed

**Comment by james-tanner** [comment]
Re-run ICE-Can after updates and returns an NA-less CSV! Believe this means this is resolved now.
Thanks @mmcauliffe!

**Comment by james-tanner** [comment]
@mmcauliffe Not sure this is worth opening, but I've gotten NAs for the first and/or last points on the Buckeye corpus:

```
> unique(subset(buckeye, is.na(F1))$time)
[1] 0.00 1.00 0.95 0.85 0.90
```

I don't necessarily think this is a problem practically (since the last tokens are customarily excluded, but it might be worth further increasing the padding for completeness.
